export const ADD_APPLICATION = 'ADD_APPLICATION';
export const CLEAN_APPLICATION = 'CLEAN_APPLICATION';
export const DELETE_ALL_APPLICATIONS = 'DELETE_ALL_APPLICATIONS';
export const UPDATE_INPUT = 'UPDATE_INPUT';
export const UPDATE_PRIORITY = 'UPDATE_PRIORITY';
export const UPDATE_DATE = 'UPDATE_DATE';
